drop table if exists DEPARTMENT;
drop table if exists CHAIR;

CREATE TABLE DEPARTMENT (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  NAME varchar(100) NOT NULL
);

CREATE TABLE CHAIR (
  DEPARTMENT INTEGER REFERENCES DEPARTMENT(ID),
  NAME varchar(100) DEFAULT NULL
);
